

# This file was *autogenerated* from the file mss_c3a_iota_annihilation5.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_200 = Integer(200)# mss_c3a_iota_annihilation5.sage -- odd model; the extension API needs a
# POLYNOMIAL modulus over the base (not a degree int): pass x^2 - 11? NO —
# unramified degree-2 extension of Q_11 needs an IRREDUCIBLE mod-11 lift of
# an irreducible quadric mod 11. Take the Teichmuller-lift style: modulus
# x^2 - d where d is a non-QR mod 11 lift: d = 7 (7 is a nonresidue mod 11).
# The doc example passes a polynomial over the base: R.<x> = Qp(11)[]; then
# K2 = Qp(11).extension(x^2 - 7).
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I2f: unramified quadratic extension via polynomial modulus ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)# 7 is a nonresidue mod 11 => unramified
out('  K2 =', K2)
poly = fA.change_ring(K2)
rts = poly.roots()
out('  roots of f over Qp(11^2): %d found' % len(rts))
if rts:
    x0 = rts[_sage_const_0 ][_sage_const_0 ]
    out('  branch point x0 = %s' % x0)
    Ru = K2['u']; (u,) = Ru._first_ngens(1)
    f_new = (poly(x0 + _sage_const_1 /u)) * u**_sage_const_8 
    out('  odd-model polynomial: %s' % f_new)
    Codd = HyperellipticCurve(f_new)
    out('  ODD model over Qp(11^2): OK')
    try:
        w = Codd.invariant_differential()
        out('  invariant differential:', w)
        out('  => coleman machinery ready on the odd model.')
    except Exception as e:
        out('  invariant differential error:', str(e)[:_sage_const_200 ])
out('=== DONE ===')

