

# This file was *autogenerated* from the file mss_c3a_iota_annihilation21.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_70 = Integer(70); _sage_const_60 = Integer(60); _sage_const_5 = Integer(5); _sage_const_80 = Integer(80)# mss_c3a_iota_annihilation21.sage -- manual Hensel sqrt (Sage's .sqrt() on
# capped-relative Qp-extension elements is unimplemented): squareness test
# via fp^60 == 1 (F_121^* has order 120), then Newton iteration z <- z/2*(1 +
# fp/z^2) doubling precision each step. Fully in-script, no API gaps.
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3o: manual Hensel sqrt ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)
poly = fA.change_ring(K2)
rts = poly.roots()
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Ru = K2['u']; (u,) = Ru._first_ngens(1)
f_new = Ru(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
fp = f_new.leading_coefficient()
out('  fp = %s' % str(fp)[:_sage_const_70 ])
# squareness: fp^60 in K2: == 1 => QR in F_121 (unit case)
t60 = fp**_sage_const_60 
is_square = (t60 == _sage_const_1 )
out('  fp^60 == 1? %s' % is_square)
if is_square:
    # Hensel: z0 = the square root mod 11: find by brute force over F_121:
    F121 = K2.residue_field() if hasattr(K2, 'residue_field') else None
    # brute force: try all lifts? simpler: Newton from z0 = fp^30 (a sqrt mod 11
    # when fp is a QR: z0 = fp^{(120+2)/4}? standard: for odd p^f, a sqrt of a QR
    # a mod q: z0 = a^{(q+1)/4} if q ≡ 3 mod 4; F_121: 121 ≡ 1 mod 4 -> need
    # general algorithm. Use Sage's sqrt on the RESIDUE FIELD (implemented):
    F121 = K2.residue_field()
    fp_red = F121(fp.unit_part() if hasattr(fp, 'unit_part') else fp)
    s_red = fp_red.sqrt()
    out('  residue sqrt: %s' % s_red)
    # lift: z = s_red in K2 via teichmuller lift + Newton:
    z = K2(s_red)
    z = z.add_precision() if hasattr(z, 'add_precision') else z
    for _ in range(_sage_const_5 ):
        z = (z + fp/z) / _sage_const_2 
    out('  Newton sqrt(fp) = %s' % str(z)[:_sage_const_80 ])
    ok = (z**_sage_const_2  - fp).valuation()
    out('  z^2 - fp valuation: %s (expect >= 8)' % ok)
    if ok >= _sage_const_7 :
        uu = _sage_const_1 /(_sage_const_0  - x0)
        vv = uu**_sage_const_4  / z
        diff = f_new.monic()(uu) - vv**_sage_const_2 
        out('  on-curve check: %s' % str(diff)[:_sage_const_80 ])
        f_final = f_new.monic()
        lst = f_final.list(); lst[-_sage_const_1 ] = K2(_sage_const_1 )
        f_final = Ru(lst)
        Codd = HyperellipticCurve(f_final)
        w = Codd.invariant_differential()
        P = Codd(uu, vv)
        Q = Codd(uu, -vv)
        val = Codd.coleman_integral(w, P, Q)
        out('  ∫_{P}^{Q} dx/(2v) = %s' % val)
out('=== DONE ===')

