

# This file was *autogenerated* from the file mss_k34_sieve2_sage_check2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_42078090600 = Integer(42078090600); _sage_const_5 = Integer(5); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_0 = Integer(0); _sage_const_256 = Integer(256); _sage_const_18432 = Integer(18432); _sage_const_128 = Integer(128); _sage_const_512 = Integer(512); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_66 = Integer(66); _sage_const_3 = Integer(3); _sage_const_23 = Integer(23); _sage_const_71 = Integer(71); _sage_const_83 = Integer(83); _sage_const_109 = Integer(109); _sage_const_113 = Integer(113); _sage_const_127 = Integer(127); _sage_const_137 = Integer(137); _sage_const_173 = Integer(173); _sage_const_181 = Integer(181); _sage_const_191 = Integer(191); _sage_const_30001 = Integer(30001); _sage_const_23736358800 = Integer(23736358800)# mss_k34_sieve2_sage_check2.sage -- decisive follow-ups (2026-09-08, hermes-win)
#  E1: X(-3G), X(-4G) exact (sign-symmetry check of the image table)
#  E2: ord_p(G) for the 10 V4 "violation" primes -> expect ord ∤ M_A (spurious)
#  E3: FILTERED stress: the 5 filed classes mod M_A vs all good primes
#      p <= 3e4 with ord_p(G) | M_A -> expect ZERO violations (reproduces §6ii)
#  E4: factor M' = 23736358800 (my re-run modulus) vs M_A
def out(*a):
    print(*a); sys.stdout.flush()

MA = _sage_const_42078090600 
KILL = [_sage_const_5 , _sage_const_11 , _sage_const_13 ]
EA = EllipticCurve([_sage_const_0 , -_sage_const_256 , _sage_const_0 , _sage_const_18432 , _sage_const_0 ])
GQ = EA(_sage_const_128 , _sage_const_512 )

def Xexact(P):
    if P.is_zero(): return 'O'
    xP, yP = P[_sage_const_0 ], P[_sage_const_1 ]
    if xP == _sage_const_0  or xP == _sage_const_4 : return 'pole'
    return QQ(_sage_const_2 *(yP + _sage_const_66 *xP)) / QQ(xP*(xP - _sage_const_4 ))

out('=== E1: exact X on negative multiples ===')
for n in (_sage_const_3 , _sage_const_4 ):
    out('  X(-%d*G) = %s' % (n, Xexact((-n) * GQ)))

out('=== E2: ord_p(G) at the V4 violation primes ===')
for p in [_sage_const_23 , _sage_const_71 , _sage_const_83 , _sage_const_109 , _sage_const_113 , _sage_const_127 , _sage_const_137 , _sage_const_173 , _sage_const_181 , _sage_const_191 ]:
    Ep = EllipticCurve(GF(p), [_sage_const_0 , -_sage_const_256 , _sage_const_0 , _sage_const_18432 , _sage_const_0 ])
    o = Ep(_sage_const_128 , _sage_const_512 ).order()
    out('  p=%d: ord=%d, ord|M_A: %s' % (p, o, MA % o == _sage_const_0 ))

out('=== E3: FILTERED stress (ord | M_A), primes <= 3e4 ===')
claim = [_sage_const_0 , _sage_const_2 , MA//_sage_const_2  - _sage_const_1 , MA - _sage_const_2 , MA - _sage_const_1 ]
nvalid = _sage_const_0 
bad = []
for p in prime_range(_sage_const_5 , _sage_const_30001 ):
    Ep = EllipticCurve(GF(p), [_sage_const_0 , -_sage_const_256 , _sage_const_0 , _sage_const_18432 , _sage_const_0 ])
    Gp = Ep(_sage_const_128 , _sage_const_512 )
    o = Gp.order()
    if MA % o != _sage_const_0 :
        continue
    nvalid += _sage_const_1 
    K = p in KILL
    sq = set(GF(p)(i)**_sage_const_2  for i in range(_sage_const_1 , p))
    for c in claim:
        P = (c % o) * Gp
        if P.is_zero():
            continue
        xP, yP = P[_sage_const_0 ], P[_sage_const_1 ]
        if xP == _sage_const_0  or xP == _sage_const_4 :
            continue
        v = (_sage_const_2 *(yP + _sage_const_66 *xP)) / (xP*(xP - _sage_const_4 ))
        ok = (v in (_sage_const_0 , _sage_const_1 )) if K else (v == _sage_const_0  or v in sq)
        if not ok:
            bad.append((p, c))
            break
out('  valid primes: %d ; violations: %s' % (nvalid, bad if bad else 'NONE'))

out('=== E4: my re-run modulus ===')
out('  M\' = 23736358800 =', factor(_sage_const_23736358800 ))
out('  M_A =', factor(MA))
out('=== DONE ===')

