

# This file was *autogenerated* from the file mss_c3a_iota_annihilation3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_150 = Integer(150); _sage_const_200 = Integer(200)# mss_c3a_iota_annihilation3.sage -- odd model via GF(11^2) default modulus
# (hermes-win, 2026-09-09). Fix of v2: no hand-rolled modulus (the preparser
# mangled it); use Sage's default Conway polynomial for GF(11^2).
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I2c: roots of f in GF(11^2) ===')
F2 = GF(_sage_const_11 **_sage_const_2 , names=('b',)); (b,) = F2._first_ngens(1)
fb = fA.change_ring(F2)
roots2 = [r for r in F2 if fb(r) == _sage_const_0 ]
out('  roots of f in F_121: %d found' % len(roots2))
if roots2:
    out('  sample: %s' % roots2[:_sage_const_4 ])
    out('=== I2d: lift to the unramified quadratic extension of Q_11 ===')
    K2 = Qp(_sage_const_11 , _sage_const_8 ).extension(x**_sage_const_2  + _sage_const_7 ) if False else Qp(_sage_const_11 , _sage_const_8 ).extension(polygen(GF(_sage_const_11 )) .minpoly() if False else None, names=('c',)); (c,) = K2._first_ngens(1)
    # simpler: construct Qp-extension by its defining polynomial directly:
    K2 = Qp(_sage_const_11 , _sage_const_8 ).extension([x**_sage_const_2  + _sage_const_7 ], 'c') if False else None
    # Sage: Qp(11,8).extension(11^2) gives the unramified degree-2 extension:
    try:
        K2 = Qp(_sage_const_11 , _sage_const_8 ).extension(_sage_const_2 , 'c')
        out('  K2 =', K2)
    except Exception as e:
        out('  K2 construction note:', str(e)[:_sage_const_150 ])
        K2 = None
    if K2 is not None:
        poly = fA.change_ring(K2)
        rts = poly.roots()
        out('  roots over Qp(11^2): %d found' % len(rts))
        if rts:
            x0 = rts[_sage_const_0 ][_sage_const_0 ]
            out('  branch point x0 = %s' % x0)
            u = polygen(K2, 'u')
            f_new = (poly(x0 + _sage_const_1 /u)) * u**_sage_const_8 
            out('  odd-model polynomial: %s' % f_new)
            Codd = HyperellipticCurve(f_new)
            out('  ODD model over Qp(11^2): OK')
            try:
                w = Codd.invariant_differential()
                out('  invariant differential:', w)
                out('  => coleman machinery ready on the odd model.')
            except Exception as e:
                out('  I3 error:', str(e)[:_sage_const_200 ])
out('=== DONE ===')

