

# This file was *autogenerated* from the file mss_c3a_iota_annihilation24.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_0 = Integer(0); _sage_const_70 = Integer(70); _sage_const_80 = Integer(80)# mss_c3a_iota_annihilation24.sage -- use the FACTORY's unramified constructor:
# Qp(11,8, print_mode=...) — the unramified extension ring is
# sage.rings.padics.factory.UnramifiedExtensionField: Qp(11, 8).unramified?
# Sage: from sage.rings.padics.factory import UnramifiedExtensionField as UE;
# K4 = UE(11, 4, 'y4', prec=8) — the unramified extension of degree 4.
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3r: UnramifiedExtensionField factory ===')
from sage.rings.padics.factory import UnramifiedExtensionField
K4 = UnramifiedExtensionField(_sage_const_11 , _sage_const_4 , 'y4', prec=_sage_const_8 )
out('  K4 = %s' % K4)
poly = fA.change_ring(K4)
rts = poly.roots()
out('  roots over the unramified quartic: %d' % len(rts))
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Rv = K4['u']; (u,) = Rv._first_ngens(1)
f_new = Rv(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
fp = f_new.leading_coefficient()
t = fp**((_sage_const_11 **_sage_const_4  - _sage_const_1 )//_sage_const_2 )
out('  fp square in K4? %s' % (t == _sage_const_1 ))
if t == _sage_const_1 :
    Fq = K4.residue_field()
    s_res = Fq(fp).sqrt()
    z = K4(s_res)
    for _ in range(_sage_const_6 ):
        z = (z + fp/z) / _sage_const_2 
    out('  sqrt(fp) = %s' % str(z)[:_sage_const_70 ])
    f_monic = f_new.monic()
    lst = f_monic.list()
    lst[-_sage_const_1 ] = K4(_sage_const_1 )
    f_final = Rv(lst)
    Codd = HyperellipticCurve(f_final)
    w = Codd.invariant_differential()
    uu = _sage_const_1 /(_sage_const_0  - x0)
    vv = uu**_sage_const_4  / z
    diff = f_final(uu) - vv**_sage_const_2 
    out('  on-curve check: %s' % str(diff)[:_sage_const_80 ])
    P = Codd(uu, vv)
    Q = Codd(uu, -vv)
    val = Codd.coleman_integral(w, P, Q)
    out('  INTEGRAL = %s' % val)
out('=== DONE ===')

