

# This file was *autogenerated* from the file mss_c3a_iota_annihilation14.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_60 = Integer(60); _sage_const_100 = Integer(100); _sage_const_200 = Integer(200); _sage_const_120 = Integer(120)# mss_c3a_iota_annihilation14.sage -- the working sanity integral: use the
# FROBENIUS-matrix route directly (matrix_of_frobenius_hyperelliptic), which
# the Sage docs show working even on curves the wrapper objects struggle with.
# The odd model f_monic (degree 7 over K2): compute the Frobenius matrix and
# the invariant differential, then the integral via coleman_integral on the
# curve object (the earlier failure was the (1+O(11^8))*y^2 rescale inside the
# HyperellipticCurve constructor: it appears when the leading coeff isn't
# literal 1; force it via the 'check=False'... simplest: divide f by its
# leading coefficient INSIDE the same ring that made it (Ru), using
# .monic() — Sage polynomial .monic() divides by lc cleanly):
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3g: Frobenius-matrix route on the odd model ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)
poly = fA.change_ring(K2)
rts = poly.roots()
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Ru = K2['u']; (u,) = Ru._first_ngens(1)
f_new = Ru(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
f_monic = f_new.monic()          # <- .monic() divides by lc properly
out('  f_monic degree: %d ; leading: %s' % (f_monic.degree(), str(f_monic.leading_coefficient())[:_sage_const_60 ]))
Codd = HyperellipticCurve(f_monic)
out('  curve: %s' % str(Codd)[:_sage_const_100 ])
try:
    w = Codd.invariant_differential()
    out('  differential OK')
    P = Codd(K2(_sage_const_0 ), K2(_sage_const_1 ))
    Q = Codd(K2(_sage_const_0 ), K2(-_sage_const_1 ))
    val = Codd.coleman_integral(w, P, Q)
    out('  ∫_{P}^{Q} dx/(2v) = %s' % val)
except Exception as e:
    out('  I3g integral error:', str(e)[:_sage_const_200 ])
# independent route: Frobenius matrix directly:
try:
    from sage.schemes.hyperelliptic_curves import monsky_washnitzer as mw
    M_frob, forms = mw.matrix_of_frobenius_hyperelliptic(Codd)
    out('  Frobenius matrix computed: %s' % str(M_frob)[:_sage_const_120 ])
except Exception as e:
    out('  Frobenius-matrix route error:', str(e)[:_sage_const_200 ])
out('=== DONE ===')

