

# This file was *autogenerated* from the file mss_c3a_iota_annihilation17.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_60 = Integer(60); _sage_const_40 = Integer(40); _sage_const_100 = Integer(100)# mss_c3a_iota_annihilation17.sage -- THE fix, fully diagnosed:
# coefficients(sparse=False) returns 9 entries for a degree-7 poly (a zero
# O(11^8) at index 8 — a CDVF padding quirk) so .pop() grabs the zero,
# which != 1 raises even though the true leading (index 7) IS 1.
# FIX: build the polynomial through a parent whose coefficient list has no
# padding: construct the HQR with Q as a LIST-based poly of exact degree 7 —
# i.e. ensure f_monic has NO zero at index 8: strip: f2 = Ru(f_monic.list())
# where .list() gives exactly degree+1 entries; then HQR(f2).
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3j: list()-based degree hygiene + HQR ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)
poly = fA.change_ring(K2)
rts = poly.roots()
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Ru = K2['u']; (u,) = Ru._first_ngens(1)
f_new = Ru(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
f_monic = f_new.monic()
# .list() gives exactly degree+1 coefficients (index 0..degree):
lst = f_monic.list()
out('  f_monic.list() length: %d (degree %d)' % (len(lst), f_monic.degree()))
out('  last entry: %s' % str(lst[-_sage_const_1 ])[:_sage_const_60 ])
# force the top to literal 1 AND rebuild with exactly 8 entries:
lst[-_sage_const_1 ] = K2(_sage_const_1 )
f_final = Ru(lst)
out('  f_final degree: %d ; leading: %s' % (f_final.degree(), str(f_final.leading_coefficient())[:_sage_const_40 ]))
from sage.schemes.hyperelliptic_curves import monsky_washnitzer as mw
HQR = mw.SpecialHyperellipticQuotientRing(f_final)
out('  HQR constructed: OK')
out('  HQR: %s' % str(HQR)[:_sage_const_100 ])
xs, ys = HQR.gens()
out('  gens OK: x, y')
out('=== DONE ===')

