

# This file was *autogenerated* from the file mss_c3a_iota_annihilation8.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_120 = Integer(120)# mss_c3a_iota_annihilation8.sage -- MW monic check workaround: after dividing
# by the leading unit, REBUILD the polynomial from its coefficient list with
# the leading coefficient replaced by the literal integer 1 (the MW wrapper's
# monic check is exact `pop() != 1`; a padded p-adic unit (1+O(11^8)) fails it).
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I2i: monic rebuild with literal top coefficient ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)
poly = fA.change_ring(K2)
rts = poly.roots()
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Ru = K2['u']; (u,) = Ru._first_ngens(1)
f_new = Ru(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
lc = f_new.leading_coefficient()
f_div = f_new / lc
# rebuild with literal 1 as leading coefficient:
coeffs = f_div.coefficients(sparse=False)   # ascending
# verify the top entry is a unit ~1:
out('  top coeff before rebuild: %s' % coeffs[-_sage_const_1 ])
coeffs[-_sage_const_1 ] = K2(_sage_const_1 )                          # literal exact 1
f_monic = Ru(coeffs)
out('  rebuilt leading: %s' % f_monic.leading_coefficient())
Codd = HyperellipticCurve(f_monic)
out('  MONIC ODD model: OK')
w = Codd.invariant_differential()
out('  invariant differential: %s' % str(w)[:_sage_const_120 ])
out('=== I3: sanity coleman integral (images of (0,±1)) ===')
try:
    xm0 = -_sage_const_1 /x0
    v = (_sage_const_1 /x0**_sage_const_4 ).sqrt()
    P1 = Codd(xm0, v)
    P2 = Codd(xm0, -v)
    val = Codd.coleman_integral(w, P1, P2)
    out('  ∫ dx/(2v) between the (0,±1) images: %s' % val)
except Exception as e:
    out('  I3 error:', str(e)[:_sage_const_250 ])
out('=== DONE ===')

