

# This file was *autogenerated* from the file mss_c3a_iota_annihilation20.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_80 = Integer(80)# mss_c3a_iota_annihilation20.sage -- resolve the twist: is f'(x0) a square
# in K2? If yes: v_final = W u^4 / sqrt(f'(x0)) lands on the monic model.
# If no: the odd model over K2 is a nontrivial twist; then construct the
# odd model over the ramified quadratic extension K2(sqrt(f'(x0))) where
# the transform is exact.
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3n: the twist check ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)
poly = fA.change_ring(K2)
rts = poly.roots()
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Ru = K2['u']; (u,) = Ru._first_ngens(1)
f_new = Ru(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
fp = f_new.leading_coefficient()     # ~ f'(x0) up to the unit normalization
out('  lc (= f\'(x0)-unit) = %s' % str(fp)[:_sage_const_80 ])
try:
    s = fp.sqrt()
    out('  sqrt(fp) = %s' % str(s)[:_sage_const_80 ])
    out('  => lc IS a K2-square; the monic model point images:')
    uu = _sage_const_1 /(_sage_const_0  - x0)
    vv = _sage_const_1  * uu**_sage_const_4  / s
    diff = f_new.monic()(uu) - vv**_sage_const_2 
    out('  on-curve check (monic model): %s' % str(diff)[:_sage_const_80 ])
    f_final = f_new.monic()
    lst = f_final.list(); lst[-_sage_const_1 ] = K2(_sage_const_1 )
    f_final = Ru(lst)
    Codd = HyperellipticCurve(f_final)
    w = Codd.invariant_differential()
    P = Codd(uu, vv)
    Q = Codd(uu, -vv)
    val = Codd.coleman_integral(w, P, Q)
    out('  ∫_{P}^{Q} dx/(2v) = %s' % val)
except Exception as e:
    out('  I3n error:', str(e)[:_sage_const_250 ])
out('=== DONE ===')

