

# This file was *autogenerated* from the file mss_c3a_iota_annihilation9.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_80 = Integer(80)# mss_c3a_iota_annihilation9.sage -- sanity integral with the CORRECT point
# images on the monic curve. Established: model constructed + monic rebuilt +
# invariant differential exists. The I3 point error: after the lc-normalization
# (lc = x0^8 exactly), the (0,±1) images are (u, v) = (-1/x0, ±1/x0^8).
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3b: sanity integral, corrected point images ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)
poly = fA.change_ring(K2)
rts = poly.roots()
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Ru = K2['u']; (u,) = Ru._first_ngens(1)
f_new = Ru(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
lc = f_new.leading_coefficient()
out('  lc = %s' % str(lc)[:_sage_const_80 ])
out('  lc == x0^8?', lc == x0**_sage_const_8 )
f_monic = f_new / lc
coeffs = f_monic.coefficients(sparse=False)
coeffs[-_sage_const_1 ] = K2(_sage_const_1 )
f_monic = Ru(coeffs)
Codd = HyperellipticCurve(f_monic)
out('  MONIC ODD model: OK')
w = Codd.invariant_differential()
xm0 = -_sage_const_1 /x0
v = _sage_const_1 /x0**_sage_const_8            # absorbing sqrt(lc) = x0^4: v_monic = v_old / x0^4
chk = f_monic(xm0) - v**_sage_const_2 
out('  curve check f_monic(-1/x0) - v^2 = %s (expect 0)' % str(chk := chk) if False else '  curve check: %s' % str(chk)[:_sage_const_80 ] if False else 'check value: %s' % chk)
try:
    P1 = Codd(xm0, v)
    P2 = Codd(xm0, -v)
    val = Codd.coleman_integral(w, P1, P2)
    out('  ∫ dx/(2v) between the (0,±1) images: %s' % val)
except Exception as e:
    out('  I3 error:', str(e)[:_sage_const_250 ])
out('=== DONE ===')

