

# This file was *autogenerated* from the file mss_k34_sieve2_sage_check.sage
from sage.all_cmdline import *   # import sage library

_sage_const_42078090600 = Integer(42078090600); _sage_const_5 = Integer(5); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_0 = Integer(0); _sage_const_256 = Integer(256); _sage_const_18432 = Integer(18432); _sage_const_128 = Integer(128); _sage_const_512 = Integer(512); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_66 = Integer(66); _sage_const_3 = Integer(3); _sage_const_1151 = Integer(1151); _sage_const_7 = Integer(7); _sage_const_202 = Integer(202); _sage_const_10 = Integer(10); _sage_const_401 = Integer(401); _sage_const_300000 = Integer(300000); _sage_const_50000 = Integer(50000); _sage_const_20001 = Integer(20001)# mss_k34_sieve2_sage_check.sage -- SageMath 10.9 independent re-verification
# of [mss-k34-sieve2] (A-side). hermes-win, 2026-09-08.
# NOTE: ad-hoc probes written earlier this session used the WRONG map numerator
# 2y+66x instead of the filed 2(y+66x) = 2y+132x (notes.md ~line 964:
# X = 2(y+66x)/(x(x-4)); mss_k34_sieve2_claude_check.py line 79). Their
# apparent kills of the M/2-1 class were spurious. The identity X(G) = 35/31
# (V1 below) validates the correct map.
# Sections:
#   V1 exact X identities on ~E_A: y^2 = x^3 - 256x^2 + 18432x, G = (128,512)
#   V2 pole-extension lever: X(2G) = 1151/66 (0/0), mod 13 == 7 (nonresidue)
#   C  independent sieve re-run: killing {5,11,13} + grow <= 400
#      + hunt <= 5e4 (ord | M) -> survivors should be {0, 2, M/2-1, -2, -1}
#   D  survivor stress: exact n against ALL primes <= 2e4
import sys
def out(*a):
    print(*a); sys.stdout.flush()

MA = _sage_const_42078090600 
KILL = [_sage_const_5 , _sage_const_11 , _sage_const_13 ]
EA = EllipticCurve([_sage_const_0 , -_sage_const_256 , _sage_const_0 , _sage_const_18432 , _sage_const_0 ])

def ctx(p):
    Ep = EllipticCurve(GF(p), [_sage_const_0 , -_sage_const_256 , _sage_const_0 , _sage_const_18432 , _sage_const_0 ])
    Gp = Ep(_sage_const_128 , _sage_const_512 )
    o = Gp.order()
    K = p in KILL
    sq = set(GF(p)(i)**_sage_const_2  for i in range(_sage_const_1 , p)) if not K else None
    return (Gp, o, K, sq)

def keep(n, c4):
    Gp, o, K, sq = c4
    P = (n % o) * Gp
    if P.is_zero(): return True          # O: X = infinity, degenerate
    xP, yP = P[_sage_const_0 ], P[_sage_const_1 ]
    if xP == _sage_const_0  or xP == _sage_const_4 : return True   # pole class (survives mod p; 2c lever handles)
    v = (_sage_const_2 *(yP + _sage_const_66 *xP)) / (xP*(xP - _sage_const_4 ))
    if K: return v in (_sage_const_0 , _sage_const_1 )
    return v == _sage_const_0  or v in sq

def Xexact(P):
    if P.is_zero(): return 'O'
    xP, yP = P[_sage_const_0 ], P[_sage_const_1 ]
    if xP == _sage_const_0  or xP == _sage_const_4 : return 'pole'
    return QQ(_sage_const_2 *(yP + _sage_const_66 *xP)) / QQ(xP*(xP - _sage_const_4 ))

out('=== V1: exact X identities on ~E_A (correct map) ===')
GQ = EA(_sage_const_128 , _sage_const_512 )
for n, exp in [(_sage_const_1 , '35/31'), (-_sage_const_1 , '1'), (_sage_const_3 , '31/35'), (_sage_const_4 , '66/1151')]:
    got = Xexact(n * GQ)
    out('  X(%d*G) = %s  expect %s : %s' % (n, got, exp, str(got) == exp))
out('  X(2*G) = %s  expect pole : %s' % (Xexact(_sage_const_2 *GQ), Xexact(_sage_const_2 *GQ) == 'pole'))

out('=== V2: pole-extension lever (2c) ===')
r13 = (_sage_const_1151  * inverse_mod(_sage_const_66 , _sage_const_13 )) % _sage_const_13 
out('  1151/66 mod 13 = %d (expect 7 nonresidue): %s' % (r13, r13 == _sage_const_7 ))
ok = True
for n in range(_sage_const_2 , _sage_const_202 , _sage_const_10 ):
    got = Xexact(n * GQ)
    if got == 'pole':
        if n != _sage_const_2 :
            ok = False
            out('  unexpected pole at n=%d' % n)
        continue
    v13 = (ZZ(got.numerator()) % _sage_const_13 ) * inverse_mod(ZZ(got.denominator()) % _sage_const_13 , _sage_const_13 ) % _sage_const_13 
    if v13 != _sage_const_7 :
        ok = False
        out('  n=%d: X mod 13 = %d != 7  MISMATCH' % (n, v13))
out('  all n = 2 mod 10 in [2,192] give X = 7 mod 13: %s' % ok)

out('=== C: independent sieve re-run ===')
S = [_sage_const_0 ]; M = _sage_const_1 ; skipped = _sage_const_0 
for p in KILL:
    c4 = ctx(p); o = c4[_sage_const_1 ]
    M2 = lcm(M, o); f = M2 // M
    newS = []
    for c in S:
        for k in range(f):
            n = c + k*M
            if keep(n, c4): newS.append(n)
    S, M = newS, M2
    out('  killing p=%d: ord=%d |S|=%d M=%d' % (p, o, len(S), M))
# grow primes <= 400 ordered by ok-ratio
def ok_ratio(p):
    c4 = ctx(p); o = c4[_sage_const_1 ]
    okc = sum(_sage_const_1  for n in range(o) if keep(n, c4))
    return (QQ(okc)/QQ(o), p, o)
grow = sorted(ok_ratio(p) for p in prime_range(_sage_const_5 , _sage_const_401 ) if p not in KILL)
for ratio, p, o in grow:
    c4 = ctx(p)
    if M % o == _sage_const_0 :
        S = [c for c in S if keep(c, c4)]
    else:
        M2 = lcm(M, o); f = M2 // M
        if len(S) * f > _sage_const_300000 :
            skipped += _sage_const_1 
            continue
        newS = []
        for c in S:
            for k in range(f):
                n = c + k*M
                if keep(n, c4): newS.append(n)
        S, M = newS, M2
out('  after grow: |S|=%d M=%d skipped=%d  (claim M=MA=%d: %s)'
    % (len(S), M, skipped, MA, M == MA))
hunt = _sage_const_0 
for p in prime_range(_sage_const_401 , _sage_const_50000 ):
    c4 = ctx(p); o = c4[_sage_const_1 ]
    if MA % o == _sage_const_0  and M % o == _sage_const_0 :
        S2 = [c for c in S if keep(c, c4)]
        if len(S2) != len(S):
            hunt += _sage_const_1 
            S = S2
out('  hunt kills: %d primes; |S|=%d M=%d' % (hunt, len(S), M))
claim = sorted([_sage_const_0 , _sage_const_2 , MA//_sage_const_2  - _sage_const_1 , MA - _sage_const_2 , MA - _sage_const_1 ])
out('  survivors: %s' % sorted(S))
out('  matches claim {0, 2, M/2-1, -2, -1}: %s' % (sorted(S) == claim))
out('  density: %.3e (claim 1.19e-10)' % (float(len(S))/float(MA)))

out('=== D: survivor stress, exact n, ALL primes <= 2e4 ===')
bad = []
for p in prime_range(_sage_const_3 , _sage_const_20001 ):
    if p in (_sage_const_2 , _sage_const_3 ):
        continue            # p=2,3 bad primes: ~E_A is singular (disc divisible by 2,3)
    c4 = ctx(p)
    for n in claim:
        if not keep(n, c4):
            bad.append((p, n))
            break
out('  violations: %s' % (bad[:_sage_const_10 ] if bad else 'NONE (all 5 classes pass every prime <= 2e4)'))
out('=== DONE ===')

