

# This file was *autogenerated* from the file mss_c3a_iota_annihilation16.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_100 = Integer(100)# mss_c3a_iota_annihilation16.sage -- replicate the wrapper's monic check
# inline to see EXACTLY what it pops and why it fails.
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3i: inline replication of the monic check ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)
poly = fA.change_ring(K2)
rts = poly.roots()
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Ru = K2['u']; (u,) = Ru._first_ngens(1)
f_new = Ru(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
f_monic = f_new.monic()
out('  type(f_monic): %s ; parent: %s' % (type(f_monic).__name__, f_monic.parent()))
# the wrapper: R = Q.base_ring(); x = PolynomialRing(R, 'xx').gen(); Q.change_ring(R):
Rw = f_monic.base_ring()
out('  base_ring: %s' % Rw)
Q2 = f_monic.change_ring(K2)
out('  after change_ring: degree %s ; type %s' % (Q2.degree(), type(Q2).__name__))
cfl = Q2.coefficients(sparse=False)
out('  len(coefficients(sparse=False)): %d' % len(cfl))
out('  popped value: %s' % str(cfl[-_sage_const_1 ])[:_sage_const_100 ])
out('  popped != 1? %s' % (cfl.pop() != _sage_const_1 ))
out('  popped == 1? %s' % (cfl.pop() if False else f_monic.leading_coefficient() == _sage_const_1 ))
# ALSO: the wrapper Q.change_ring(R): R = Q.base_ring() — but in the HQR
# constructor, R is passed as None => R = Q.base_ring() = K2: same.
# The pop check uses != : for p-adics, != is numeric. So if pop == 1+O(11^8),
# != 1 should be False... test both on the actual element:
elt = Q2.leading_coefficient()
out('  direct: elt == 1 -> %s ; elt != 1 -> %s' % (elt == _sage_const_1 , elt != _sage_const_1 ))
out('  type(elt): %s' % type(elt).__name__)
out('=== DONE ===')

