

# This file was *autogenerated* from the file mss_c3a_iota_annihilation22.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_70 = Integer(70); _sage_const_80 = Integer(80)# mss_c3a_iota_annihilation22.sage -- K4 = K2(sqrt(fp)) construction: the odd
# model over the unramified quartic extension of Q_11. Route: build the
# degree-4 unramified extension directly over Q_11 with an explicit quartic
# modulus (an irreducible quartic whose reduction is the compositum), lift
# the same root x0, rebuild the transform (monic), and integrate.
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3p: unramified quartic extension ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
# irreducible quartic mod 11 containing both sqrt(7) and sqrt(fp) residues:
# try a generic quartic and check irreducibility: X^4 - 2 (2 is a NR mod 11?
# QRs mod 11: {1,3,4,5,9}: 2 NOT a QR; also need the quartic to CONTAIN the
# unramified quadratic subfield: X^4 - 2: F_11^2 inside? The splitting field
# of X^4-2 over F_11: deg = order of 2 in (Z/11)^*/gcd? x^4=2: 2 is a NR;
# the roots live in F_{11^2} iff 2^{(121-1)/2} = 1 i.e. 2 is a square in
# F_121 — squares of F_11 are squares of F_121? (11^2-1)/2 = 60: 2^60 in
# F_121: since F_121 = F_11(b): the norm map... simply: X^4 - 2 is
# irreducible mod 11 iff 2 is not a 4th power and X^2-2 is irreducible:
# 2 is a NR mod 11 => X^2-2 irreducible over F_11; X^4-2: either splits in
# F_121 (if 2 is a square in F_121) or irreducible (quartic). In F_121 =
# F_11(sqrt(7))... compute directly in Sage.
Rk2 = GF(_sage_const_11 )['T']; (T,) = Rk2._first_ngens(1)
for cand in [_sage_const_2 , _sage_const_5 , _sage_const_6 , _sage_const_7 ]:
    P4 = T**_sage_const_4  - cand
    try:
        f2 = F2.(b**_sage_const_2 +_sage_const_7 )
    except Exception:
        pass
    fac = (T**_sage_const_4  - cand).factor()
    if list(fac)[_sage_const_0 ][_sage_const_0 ].degree() == _sage_const_4 :
        out('  X^4 - %d irreducible mod 11 -> contains F_11^4' % cand)
        break
K4 = Qp(_sage_const_11 , _sage_const_8 ).extension(X**_sage_const_4  - _sage_const_2 ) if False else None
Rq = K11['Y']; (Y,) = Rq._first_ngens(1)
K4 = Qp(_sage_const_11 , _sage_const_8 ).extension(Y**_sage_const_4  - _sage_const_2 , 'y')
out('  K4 = %s' % K4)
poly = fA.change_ring(K4)
rts = poly.roots()
out('  roots over Qp(11^4): %d' % len(rts))
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Rv = K4['u']; (u,) = Rv._first_ngens(1)
f_new = Rv(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
fp = f_new.leading_coefficient()
# now sqrt via residue: F_{11^4}^* order (11^4-1): square test:
t = fp**((_sage_const_11 **_sage_const_4  - _sage_const_1 )//_sage_const_2 )
out('  fp^((11^4-1)/2) == 1? %s' % (t == _sage_const_1 ))
if t == _sage_const_1 :
    Fq = K4.residue_field()
    s_res = Fq(fp).sqrt()
    z = K4(s_res)
    for _ in range(_sage_const_5 ):
        z = (z + fp/z) / _sage_const_2 
    out('  sqrt(fp) = %s' % str(z)[:_sage_const_70 ])
    f_monic = f_new.monic()
    lst = f_monic.list(); lst[-_sage_const_1 ] = K4(_sage_const_1 )
    f_mon2 = Rv(lst)
    Codd = HyperellipticCurve(f_mon2 := f_mon2 if False else f_mon2 if False else f_mon2 if False else Rv(lst))
    Codd = HyperellipticCurve(Rv(lst))
    w = Codd.invariant_differential()
    uu = _sage_const_1 /(_sage_const_0  - x0)
    vv = uu**_sage_const_4  / z
    diff = f_mon2(uu) - vv**_sage_const_2 
    out('  on-curve check: %s' % str(diff)[:_sage_const_80 ])
    P = Codd(uu, vv)
    Q = Codd(uu, -vv)
    val = Codd.coleman_integral(w, P, Q)
    out('  ∫_{P}^{Q} dx/(2v) = %s' % val)
out('=== DONE ===')

