

# This file was *autogenerated* from the file mss_c3a_iota_annihilation15.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_40 = Integer(40); _sage_const_20 = Integer(20)# mss_c3a_iota_annihilation15.sage -- direct MW-ring construction: skip the
# HyperellipticCurve object entirely (its constructor's internal scaling is
# what breaks the wrapper's monic check) and instantiate
# SpecialHyperellipticQuotientRing on the RAW monic polynomial f_monic.
# The correct import names (from the module grep): SpecialHyperellipticQuotientRing
# exists; the differential class is SpecialCubicQuotientRingElement-based —
# differentials via HQR.gens() and the element .diff() methods.
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3h: raw MW ring on the monic polynomial ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)
poly = fA.change_ring(K2)
rts = poly.roots()
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Ru = K2['u']; (u,) = Ru._first_ngens(1)
f_new = Ru(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
f_monic = f_new.monic()
out('  f_monic degree: %d ; leading: %s' % (f_monic.degree(), f_monic.leading_coefficient()))
from sage.schemes.hyperelliptic_curves import monsky_washnitzer as mw
try:
    HQR = mw.SpecialHyperellipticQuotientRing(f_monic)
    out('  HQR from raw polynomial: OK')
    xs, ys = HQR.gens()
    out('  gens: x = %s ; y = %s' % (str(xs)[:_sage_const_40 ], str(ys)[:_sage_const_40 ]))
    # invariant differential dx/(2y): the element (1) in the differential module:
    # the differential construction on SpecialHyperellipticQuotientElement:
    # w = dx/(2y): represented as HQR element with the .diff? Check methods:
    methods = [m for m in dir(HQR) if not m.startswith('_')]
    out('  HQR methods: %s' % methods[:_sage_const_20 ])
except Exception as e:
    out('  I3h error:', str(e)[:_sage_const_250 ])
out('=== DONE ===')

