

# This file was *autogenerated* from the file mss_c3a_iota_annihilation25.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_3 = Integer(3); _sage_const_7 = Integer(7); _sage_const_5 = Integer(5); _sage_const_9 = Integer(9); _sage_const_0 = Integer(0); _sage_const_80 = Integer(80)# mss_c3a_iota_annihilation25.sage -- unramified quartic with a VERIFIED
# irreducible modulus (X^4 - 2 factors over F_11 into two quadratics since
# every F_11 element is a square in F_121 — found by reasoning; test
# candidates in-script with the factory's own is_unramified check).
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3s: find an irreducible quartic mod 11 ===')
from sage.rings.padics.factory import is_unramified
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
modulus = None
for cand_poly in [X**_sage_const_4  + X + _sage_const_2 , X**_sage_const_4  + X + _sage_const_3 , X**_sage_const_4  + _sage_const_2 *X + _sage_const_3 , X**_sage_const_4  + _sage_const_3 *X + _sage_const_7 ,
                  X**_sage_const_4  + X + _sage_const_5 , X**_sage_const_4  + _sage_const_5 *X + _sage_const_2 , X**_sage_const_4  + _sage_const_2 *X + _sage_const_2 , X**_sage_const_4  + X + _sage_const_9 ]:
    if is_unramified(cand_poly):
        modulus = cand_poly
        out('  unramified quartic found: %s' % cand_poly)
        break
if modulus is None:
    # try more systematically: all X^4 + aX^2 + b with irreducible
    for a in range(_sage_const_11 ):
        for bcoef in range(_sage_const_1 , _sage_const_11 ):
            P = X**_sage_const_4  + a*X**_sage_const_2  + bcoef
            if is_unramified(P):
                modulus = P
                out('  unramified quartic: %s' % P)
                break
        if modulus is not None:
            break
if modulus is not None:
    K4 = Qp(_sage_const_11 , _sage_const_8 ).extension(modulus, names=('y4',)); (y4,) = K4._first_ngens(1)
    out('  K4 = %s' % K4)
    poly = fA.change_ring(K4)
    rts = poly.roots()
    out('  roots over K4: %d' % len(rts))
    x0 = rts[_sage_const_0 ][_sage_const_0 ]
    Rv = K4['u']; (u,) = Rv._first_ngens(1)
    f_new = Rv(_sage_const_0 )
    for j in range(poly.degree() + _sage_const_1 ):
        aj = poly[j]
        f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
    fp = f_new.leading_coefficient()
    t = fp**((_sage_const_11 **_sage_const_4  - _sage_const_1 )//_sage_const_2 )
    out('  fp square in K4? %s' % (t == _sage_const_1 ))
    if t == _sage_const_1 :
        Fq = K4.residue_field()
        s_res = Fq(fp).sqrt()
        z = K4(s_res)
        for _ in range(_sage_const_6 ):
            z = (z + fp/z) / _sage_const_2 
        out('  sqrt(fp) ok; on-curve check next')
        f_mon2 = f_new.monic()
        lst2 = f_mon2.list()
        lst2[-_sage_const_1 ] = K4(_sage_const_1 )
        f_final = Rv(lst2)
        Codd = HyperellipticCurve(f_final)
        w = Codd.invariant_differential()
        uu = _sage_const_1 /(_sage_const_0  - x0)
        vv = uu**_sage_const_4  / z
        diff = f_final(uu) - vv**_sage_const_2 
        out('  on-curve check: %s' % str(diff)[:_sage_const_80 ])
        P = Codd(uu, vv)
        Q = Codd(uu, -vv)
        val = Codd.coleman_integral(w, P, Q)
        out('  INTEGRAL = %s' % val)
out('=== DONE ===')

