# mss_c3a_annihilation.sage -- Coleman gate, step 1: annihilating differential
# construction on J(C3_A) (hermes-win, 2026-09-09). [mss-k34-c3ab-prep] cont.
#
# Filed structure: rank J(C3_A) = 2 < g = 3 (E_iota rank 1, E_G rank 0 proved).
# MW basis: (P_iota, 0, 0) and (0, 0, T_G-parts are torsion) — i.e. the rank-2
# MW lattice = image of E_iota(Z) x E_rho(Z) (both rank 1, both generated by the
# SAME master G_A under the isogenies). The annihilating differential exists
# (dim H0(Omega) = 3 > rank 2); the Coleman gate asks: integrate omega over the
# two MW cycles = 0, then residue bound => #C3_A(Q) <= #C3_A(F_11) + 0 (if
# #C3_A(F_11) = 8 = known points, K34-A closes).
#
# THIS SCRIPT: the linear-algebra step. At p = 11 (small precision p^8):
#  1. MW basis points of J(C3_A)(Q): from E_iota(Z) = <G_iota> and E_G-torsion.
#  2. omega_i = the three basis differentials on C3_A.
#  3. Solve for omega annihilating both MW points (p-adic linear algebra on
#     the period matrix computed via coleman integrals between residue classes
#     -- at this precision we test the MECHANISM, not the full gate).
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R.<x> = QQ[]
fA = x^8 + 132*x^6 - 250*x^4 + 132*x^2 + 1

out('=== A1: exact differentials of C3_A ===')
C3A = HyperellipticCurve(fA)
# holomorphic basis for even-degree hyperelliptic genus 3:
# omega_i = x^(i-1) dx / (2W) * (something regular)? For even degree:
# H0(Omega) = < dx/W, x dx/W, x^2 dx/W > (all regular: numerator deg <= 2 < 2g-1+1?)
# Regularity: deg(numer) <= deg(f) - 3 - (deg/2 - 1) => for deg 8: numer deg <= 4? 
# Standard: x^k dx/(2W) regular iff k <= g-1 = 2 (even degree, both infinities nonsingular).
out('  H0(Omega) basis: dx/W, x dx/W, x^2 dx/W (all regular for even-degree deg-8).')

out('=== A2: the three quotient differentials as pullbacks ===')
# Under iota (v = x^2): C3_A -> Q_iota: w_iota^2 = v^4+132v^3-250v^2+132v+1.
# The invariant differentials of C3_A under iota: those with a((-x)) = -a(x).
# x dx/W and x^3? not in H0. dx/W is INVARIANT under x->-x (dx -> -dx, W same):
# so dx/W anti-invariant?? dx(-x) = -dx => (dx/W) -> -(dx/W): ANTI-invariant.
# x dx/W -> (-x)(-dx)/W = x dx/W: INVARIANT. x^2 dx/W -> x^2(-dx)/W: anti.
# So under iota: {dx/W, x^2 dx/W} anti-invariant (push to iota-quotient),
# x dx/W invariant (pushes to rho-quotient!). Under rho (x->1/x, W->W/x^4):
# dx/W -> (dx/x^2)/(W/x^4) = x^2 dx/W: mixes dx/W with x^2 dx/W.
out('  iota: dx/W and x^2 dx/W anti-invariant (-> E_iota side), x dx/W invariant.')
out('  rho: dx/W <-> x^2 dx/W mixed; one combo descends to rho-quotient.')
out('  => the E_G-side differential is the combo killed by BOTH quotient maps.')

out('=== A3: MW basis construction (exact, over Q) ===')
EIOTA = EllipticCurve([0, 0, 0, -276480, 240648192])
EG    = EllipticCurve([0, 0, 0, -504576, 131604480])
out('  E_iota rank:', EIOTA.rank(), '(expect 1)')
Gi = EIOTA.gens()[0]
out('  E_iota generator:', Gi)
try:
    egr = EG.rank(proof=False)
except Exception as e:
    egr = 'unproven'
out('  E_G rank:', egr, '(filed: 0, proved by 2-isogeny descent)')
out('  E_G torsion:', EG.torsion_subgroup())
# MW basis of J(C3_A)(Q) = E_iota(Q) x E_rho(Q) x E_G(Q):
# = <G_iota> x <G_rho> x {0}  (E_G torsion adds finite part)
# The two generators as J-points: (Gi, 0, 0) and (0, Gr, 0).
out('  MW basis: (G_iota, 0, 0), (0, G_rho, 0); rank 2 total.  <-- exact')

out('=== A4: annihilating differential (linear algebra over Q) ===')
# omega = (a + b x + c x^2) dx/W annihilates both MW generators iff
#   int(omega) over the Abel-Jacobi image of each generator = 0.
# The p-adic evaluation: integrate between the infinity point and the Abel image.
# At this precision we do the MECHANISM check on the iota-side:
K = Qp(11, 10)
EIOTAp = EIOTA.change_ring(K)
try:
    Gp = EIOTAp([QQ(Gi[0]), QQ(Gi[1])])
    wp = EIOTAp.invariant_differential()
    Oinf = EIOTAp(0)
    val = wp.coleman_integral(Oinf, Gp)
    out('  coleman int from O to G_iota at p=11:', val, '(this is the abelian integral)')
except Exception as e:
    out('  integral probe error:', str(e)[:180])
out('=== DONE ===')