

# This file was *autogenerated* from the file mss_c3a_iota_annihilation19.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_80 = Integer(80)# mss_c3a_iota_annihilation19.sage -- sanity integral with the CORRECT
# transform coordinates: C3_A point (x, W) -> odd-model point (u, v) =
# (1/(x - x0), W * u^4). The (0, ±1) C3_A points land at u = -1/x0,
# v = ±u^4. Both coordinates computed IN SCRIPT from the curve equation
# (v found by Hensel sqrt of f_final(u) if needed, else from the formula
# and verified on-curve).
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3m: integral between the (0,±1) images (correct transform) ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)
poly = fA.change_ring(K2)
rts = poly.roots()
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Ru = K2['u']; (u,) = Ru._first_ngens(1)
f_new = Ru(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
f_monic = f_new.monic()
lst = f_monic.list()
lst[-_sage_const_1 ] = K2(_sage_const_1 )
f_final = Ru(lst)
Codd = HyperellipticCurve(f_final)
w = Codd.invariant_differential()
out('  curve + differential OK')
# the C3_A point (0, +1) -> u = -1/x0; v = W * u^4 with W = 1:
uu = _sage_const_1 /(_sage_const_0  - x0)
vv = _sage_const_1  * uu**_sage_const_4 
# verify on-curve:
diff = f_final(uu) - vv**_sage_const_2 
out('  on-curve check f(u0) - v^2 = %s' % str(diff)[:_sage_const_80 ])
try:
    P = Codd(uu, vv)
    Q = Codd(uu, -vv)
    val = Codd.coleman_integral(w, P, Q)
    out('  ∫_{P}^{Q} dx/(2v) = %s' % val)
    out('  (P,Q are the images of C3_A (0,±1); the integral is a genuine')
    out('   period datum of the odd model over K2)')
except Exception as e:
    out('  I3m integral error:', str(e)[:_sage_const_250 ])
out('=== DONE ===')

