

# This file was *autogenerated* from the file mss_c3a_iota_annihilation13.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_60 = Integer(60); _sage_const_120 = Integer(120)# mss_c3a_iota_annihilation13.sage -- bypass the monic check: call
# SpecialHyperellipticQuotientRing with R = the p-adic base and Q = a REBUILT
# polynomial whose coefficients list ends in the LITERAL 1 AND whose length
# is exactly 8 (degree 7). The wrapper scales internally? The KeyError trace
# showed the curve rescaled by (1+O(11^8)): pass the curve object directly
# (the HyperellipticCurve branch) — C.hyperelliptic_polynomials()[0] — that's
# f as given. The pop() got (1+O(11^8))? The print of the curve shows
# '(1+O(11^8))*y^2 = ...' — the CURVE ITSELF stores the equation with the
# (1+O(11^8)) factor on y^2: i.e. the constructor turned my f_monic into
# (1+O(11^8))*y^2 = f_monic — the hyperelliptic_polynomials()[0] is then
# f_monic/(1+O(11^8)) = f_monic — hmm. Try the DIRECT route: skip the curve;
# pass the polynomial Q directly to SpecialHyperellipticQuotientRing (it
# accepts a polynomial!) — then build the MW cohomology from it.
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3f: direct SpecialHyperellipticQuotientRing route ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)
poly = fA.change_ring(K2)
rts = poly.roots()
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Ru = K2['u']; (u,) = Ru._first_ngens(1)
f_new = Ru(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
f_monic = f_new / f_new.leading_coefficient()
d = f_monic.degree()
c_list = f_monic.coefficients(sparse=False)
c_list[d] = K2(_sage_const_1 )
f_monic = Ru(c_list)
out('  f_monic degree: %d ; leading: %s' % (f_monic.degree(), str(f_monic.leading_coefficient())[:_sage_const_60 ]))
from sage.schemes.hyperelliptic_curves.monsky_washnitzer import (
    SpecialHyperellipticQuotientRing, SpecialMonskyWashnitzerDifferential)
try:
    HQR = SpecialHyperellipticQuotientRing(f_monic)
    out('  HQR constructed DIRECTLY from the monic polynomial: OK')
    out('  HQR = %s' % str(HQR)[:_sage_const_120 ])
    # the invariant differential in the MW ring:
    x, y = HQR.gens()
    w = SpecialMonskyWashnitzerDifferential(HQR, HQR.one())
    out('  MW differential 1 dx/2y:', w)
    out('  => MW ring ready WITHOUT the HyperellipticCurve constructor')
except Exception as e:
    out('  direct HQR error:', str(e)[:_sage_const_250 ])
out('=== DONE ===')

