

# This file was *autogenerated* from the file mss_c3a_iota_annihilation18.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_200 = Integer(200)# mss_c3a_iota_annihilation18.sage -- HQR WORKS. Now the sanity integral on
# the MW ring directly: differential w = 1 (dx/2y), points... the MW ring
# doesn't carry points; the coleman_integral API needs the curve object for
# P, Q. Route: the docs' matrix_of_frobenius_hyperelliptic needs the curve.
# Alternative within the MW ring: compute the Frobenius matrix on H^1(MW)
# via mw.frobenius_expansion_by_newton(Q, p, M) and the REDUCTION machinery
# — this is exactly what coleman_integral does internally. The integrals
# between K2-rational points: the docs route used HK.coleman_integral on the
# curve. Our curve object CAN be built if we hand Sage the polynomial in a
# way that survives: HyperellipticCurve(f_final) raised 'must be monic'
# because the constructor ALSO does the rescale? Test: HyperellipticCurve
# with check_squarefree=False and the LIST-built f_final:
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3k: curve from f_final + integral ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)
poly = fA.change_ring(K2)
rts = poly.roots()
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Ru = K2['u']; (u,) = Ru._first_ngens(1)
f_new = Ru(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
f_monic = f_new.monic()
lst = f_monic.list()
lst[-_sage_const_1 ] = K2(_sage_const_1 )
f_final = Ru(lst)
try:
    Codd = HyperellipticCurve(f_final)
    out('  curve constructed: OK')
    w = Codd.invariant_differential()
    out('  differential OK')
    P = Codd(K2(_sage_const_0 ), K2(_sage_const_1 ))
    Q = Codd(K2(_sage_const_0 ), K2(-_sage_const_1 ))
    val = Codd.coleman_integral(w, P, Q)
    out('  ∫_{P}^{Q} dx/(2v) = %s' % val)
except Exception as e:
    out('  curve/integral error:', str(e)[:_sage_const_250 ])
    # fallback: the MW-ring direct integral (no curve object):
    try:
        out('  fallback: MW-ring Frobenius route')
        HQR = mw.SpecialHyperellipticQuotientRing(f_final)
        from sage.schemes.hyperelliptic_curves import monsky_washnitzer as mwmod
        p = _sage_const_11 
        M_frob, forms = mwmod.frobenius_expansion_by_newton(f_final, p, _sage_const_8 )
        out('  Frobenius expansion: OK (matrix %sx%s)' % (len(M_frob), len(M_frob[_sage_const_0 ]) if M_frob else _sage_const_0 ))
    except Exception as e2:
        out('  fallback error:', str(e2)[:_sage_const_200 ])
out('=== DONE ===')

