

# This file was *autogenerated* from the file mss_c3a_iota_annihilation12.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_80 = Integer(80)# mss_c3a_iota_annihilation12.sage -- monic fix v2: replace the coefficient at
# index = f_monic.degree() (not coeffs[-1], which is padding-sensitive).
# Also print the degree and leading coefficient before/after.
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3e: correct monic normalization ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)
poly = fA.change_ring(K2)
rts = poly.roots()
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Ru = K2['u']; (u,) = Ru._first_ngens(1)
f_new = Ru(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
out('  f_new degree: %d ; f\'(x0) = leading = %s' % (f_new.degree(), str(f_new.leading_coefficient())[:_sage_const_80 ]))
f_monic = f_new / f_new.leading_coefficient()
d = f_monic.degree()
out('  f_monic degree: %d' % d)
out('  f_monic leading (index %d): %s' % (d, f_monic.coefficient(d)))
out('  f_monic leading == 1?', f_monic.coefficient(d) == _sage_const_1 )
if f_monic.coefficient(d) != _sage_const_1 :
    # replace just that coefficient via the polynomial constructor:
    c_list = f_monic.coefficients(sparse=False)
    d_idx = d
    c_list[d_idx] = K2(_sage_const_1 )
    f_monic = Ru(c_list)
    out('  replaced coefficient at index %d with literal 1' % d_idx)
    out('  new degree: %d ; new leading: %s' % (f_monic.degree(), f_monic.coefficient(f_monic.degree())))
Codd = HyperellipticCurve(f_monic)
w = Codd.invariant_differential()
out('  model + differential OK')
P = Codd(K2(_sage_const_0 ), K2(_sage_const_1 ))
Q = Codd(K2(_sage_const_0 ), K2(-_sage_const_1 ))
val = Codd.coleman_integral(w, P, Q)
out('  ∫_{P}^{Q} dx/(2v) = %s' % val)
out('=== DONE ===')

