

# This file was *autogenerated* from the file mss_c3a_iota_annihilation11.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_132 = Integer(132); _sage_const_6 = Integer(6); _sage_const_250 = Integer(250); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_90 = Integer(90)# mss_c3a_iota_annihilation11.sage -- sanity integral between the two
# INFINITY-point images at u = 0 on the odd model: P = Codd(0, 1),
# Q = Codd(0, -1) (both K2-rational, no sqrt needed — f_monic(0) = 1 exactly).
import sys, time
def out(*a):
    print(*a); sys.stdout.flush()
T0 = time.time()
def el():
    return '%.0fs' % (time.time() - T0)

R = QQ['x']; (x,) = R._first_ngens(1)
fA = x**_sage_const_8  + _sage_const_132 *x**_sage_const_6  - _sage_const_250 *x**_sage_const_4  + _sage_const_132 *x**_sage_const_2  + _sage_const_1 

out('=== I3d: integral between the infinity images (u=0) ===')
K11 = Qp(_sage_const_11 , _sage_const_8 )
Rk = K11['X']; (X,) = Rk._first_ngens(1)
K2 = K11.extension(X**_sage_const_2  - _sage_const_7 , names=('c',)); (c,) = K2._first_ngens(1)
poly = fA.change_ring(K2)
rts = poly.roots()
x0 = rts[_sage_const_0 ][_sage_const_0 ]
Ru = K2['u']; (u,) = Ru._first_ngens(1)
f_new = Ru(_sage_const_0 )
for j in range(poly.degree() + _sage_const_1 ):
    aj = poly[j]
    f_new += aj * (x0*u + _sage_const_1 )**j * u**(_sage_const_8  - j)
lc = f_new.leading_coefficient()
f_monic = f_new / lc
coeffs = f_monic.coefficients(sparse=False)
coeffs[-_sage_const_1 ] = K2(_sage_const_1 )
f_monic = Ru(coeffs)
Codd = HyperellipticCurve(f_monic)
w = Codd.invariant_differential()
out('  f_monic(0) = %s (expect the transformed constant: f(0)/lc·...)' % str(f_monic(_sage_const_0 ))[:_sage_const_90 ])
try:
    P = Codd(K2(_sage_const_0 ), K2(_sage_const_1 ))
    Q = Codd(K2(_sage_const_0 ), K2(-_sage_const_1 ))
    out('  points P=(0,1), Q=(0,-1) constructed OK')
    val = Codd.coleman_integral(w, P, Q)
    out('  ∫_{P}^{Q} dx/(2v) = %s' % val)
    out('  (this is the sanity integral: two K2-rational points, same u)')
except Exception as e:
    out('  I3d error:', str(e)[:_sage_const_250 ])
out('=== DONE ===')

