# Smoke test v2: Shioda character formalism for Fermat hypersurfaces.
# X_m^n in P^{n+1} has d = n+2 coordinates; characters are d-tuples
# a=(a_0..a_{d-1}), 0 < a_i < m, sum(a) = 0 mod m (these index the
# eigenspaces of G = mu_m^d/Delta on H^n_prim).
# Hodge-type rule (validated against Fermat quartic surface):
#   E_a subset H^{n-j,j}  iff  sum(a) = (j+1)*m.
# So for the FOURFOLD: (2,2)-classes <=> sum(a) = 3m exactly.

import itertools, math
from collections import Counter

def relevant(m, d):
    for a in itertools.product(range(1, m), repeat=d):
        s = sum(a)
        if s % m == 0:
            yield a, s

# --- Validation: Fermat quartic surface (m=4, d=4).
prof = Counter(s for _, s in relevant(4, 4))
t11 = prof.get(8, 0)          # (1,1): j=1 -> sum=2m=8
ttr = prof.get(4, 0) + prof.get(12, 0)  # (2,0)+(0,2)
tot = sum(prof.values())
print("quartic surface: total relevant = %d (expect 21 = b2-1)" % tot)
print("  (1,1) eigenspaces = %d (expect 19), transcendental = %d (expect 2)"
      % (t11, ttr))
assert (tot, t11, ttr) == (21, 19, 2), "quartic validation FAILED"
print("VALIDATED (rho=20, tr rank 2).\n")

# --- Validation: Fermat cubic surface (m=3, d=4): known b2=7, rho=7 (rational).
prof3 = Counter(s for _, s in relevant(3, 4))
print("cubic surface profile:", dict(prof3),
      "-> (1,1) count =", prof3.get(6, 0), "(expect 6 = rho-1)")

def fourfold_census(m, verbose=True):
    """Fermat fourfold X_m^4 in P^5: d=6, (2,2) <=> sum = 3m.
    Returns (num (2,2)-characters, num Galois orbits)."""
    chars = [a for a, s in relevant(m, 6) if s == 3 * m]
    units = [u for u in range(1, m) if math.gcd(u, m) == 1]
    seen = set()
    n_orb = 0
    for a in chars:
        if a in seen:
            continue
        orb = set()
        for u in units:
            orb.add(tuple((u * x) % m for x in a))
        seen |= orb
        n_orb += 1
    if verbose:
        print("m=%3d: (2,2)-characters = %7d, Galois orbits = %6d"
              % (m, len(chars), n_orb))
    return len(chars), n_orb

print("Fermat fourfold census size (2,2)-characters, sum=3m:")
for m in (5, 6, 7, 9, 10, 11, 13, 25):
    fourfold_census(m)

# Known cross-check (Ran/Shioda): m prime (5,7,11,13) => cohomology
# generated by linear subspaces => HC holds; these should be fully
# 'decomposable' -- the decomposability test is the next pipeline stage
# (Shioda semigroup M_m), not part of this smoke test.